source 'https://github.com/CocoaPods/Specs.git'

platform :osx, '10.9'

inhibit_all_warnings!

target :SampleOSXCocoaPodsProject do
	pod 'BRFullTextSearch', 		:path => '../'
	pod 'MagicalRecord',			'2.2'
end

